; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Picmarker"
#define MyAppVersion "1.3"
#define MyAppPublisher "魏子昂软件工作室"
#define MyAppURL "https://www.github.com/WZA-Leon/Picmarker"
#define MyAppExeName "launcher_win10_11.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EADC2A1B-B7A8-4C07-8670-1F532787CD30}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; 安装包自身图标（编译时路径）
SetupIconFile=icon.ico
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\WZA\Desktop\Picchooser\LICENSE
; 非管理员安装模式：安装到当前用户 AppData，无需管理员权限
PrivilegesRequired=lowest
OutputDir=C:\Users\WZA\Desktop
OutputBaseFilename=Picmarker_setup
SolidCompression=yes
WizardStyle=modern dynamic polar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinese"; MessagesFile: "compiler:Languages\Chinese.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\WZA\Desktop\111111\Win10_11\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\bootstrap_runtime_win10_11.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\bootstrap_runtime_win10_11.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\config.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\extract_blind.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\hidden_watermark.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\launcher_win10_11.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\main.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\progress_util.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\settings.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\ui_main.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\ui_settings.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\ui_watermark.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\utils.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WZA\Desktop\111111\Win10_11\icons\*"; DestDir: "{app}\icons"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\WZA\Documents\runtime\*"; DestDir: "{app}\runtime"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKCU; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


